[package]
name = "rust_wcloud"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.7.3"
jieba-rs = { version = "0.7", features = ["tfidf", "textrank"] }
ab_glyph = "0.2.20"
image = "0.24.6"
nanorand = "0.7.0"
palette = "0.6.1"